export default [
  {
    "name": "RIYADH - الرياض",
    "title_ar": "الرياض",
    "title_en": "RIYADH",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "NV25GlPuOnQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SHAKRAA - شقراء",
    "title_ar": "شقراء",
    "title_en": "SHAKRAA",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "dDYGE17HCcg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-DWADMY - الدوادمي",
    "title_ar": "الدوادمي",
    "title_en": "AL-DWADMY",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "ZGUL0hN7D9M=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-KWAYEYA - القويعيه",
    "title_ar": "القويعيه",
    "title_en": "AL-KWAYEYA",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "LPLQ5MSAofw=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AFIF - عفيف",
    "title_ar": "عفيف",
    "title_en": "AFIF",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "UNIkOZHdccs=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-MAJMAA - المجمعه",
    "title_ar": "المجمعه",
    "title_en": "AL-MAJMAA",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "UM9SWVjlAgs=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-ZLFA - الزلفي",
    "title_ar": "الزلفي",
    "title_en": "AL-ZLFA",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "zKBzR4m/HMc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "HRYMLAA - حريملاء",
    "title_ar": "حريملاء",
    "title_en": "HRYMLAA",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "/mPNV3q1bw8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "THADEK - ثادق",
    "title_ar": "ثادق",
    "title_en": "THADEK",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "1nC0T+SdHO0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "HAWTAT BNEY TAMEEM - حوطة بني تميم",
    "title_ar": "حوطة بني تميم",
    "title_en": "HAWTAT BNEY TAMEEM",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "QObkVpmQ9sQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-KHARJ - الخرج",
    "title_ar": "الخرج",
    "title_en": "AL-KHARJ",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "4o7x7Ef6D7c=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-AFLAJ - الأفلاج",
    "title_ar": "الأفلاج",
    "title_en": "AL-AFLAJ",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "FOrMQg33iB8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "WADY AL-DAWASER - وادى الدواسر",
    "title_ar": "وادى الدواسر",
    "title_en": "WADY AL-DAWASER",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "m1qAB9fuVxc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SDER - سدير",
    "title_ar": "سدير",
    "title_en": "SDER",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "DEAD09SoS98=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SHOABAT AL-GENSYAH - شعبة الجنسية",
    "title_ar": "شعبة الجنسية",
    "title_en": "SHOABAT AL-GENSYAH",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "nn3NVNwvU5Y=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-SALEEL - السليل",
    "title_ar": "السليل",
    "title_en": "AL-SALEEL",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "SQlzG0WyzMs=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-GHAT - الغاط",
    "title_ar": "الغاط",
    "title_en": "AL-GHAT",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "sfND4g6dvsA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "HAWTET SDER - حوطة سدير",
    "title_ar": "حوطة سدير",
    "title_en": "HAWTET SDER",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "PHuXPP2Xals=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-MZAHMYA - المزاحمية",
    "title_ar": "المزاحمية",
    "title_en": "AL-MZAHMYA",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "z/+3/Qhn40A=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ROMAH - رماح",
    "title_ar": "رماح",
    "title_en": "ROMAH",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "siEoRCx5SNQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALDEREIAH - الدرعية",
    "title_ar": "الدرعية",
    "title_en": "ALDEREIAH",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "zRaSlhneZdc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "TAMEIR - تمير",
    "title_ar": "تمير",
    "title_en": "TAMEIR",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "aiAQYW0+mRU=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-RWEDAH - الرويضة",
    "title_ar": "الرويضة",
    "title_en": "AL-RWEDAH",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "TqT+fyxN8pg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-DLM - الدلم",
    "title_ar": "الدلم",
    "title_en": "AL-DLM",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "Ft/4xA3AMo4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-JAMSH - الجمش",
    "title_ar": "الجمش",
    "title_en": "AL-JAMSH",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "R8Ax3PFdqrk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SAJER - ساجر",
    "title_ar": "ساجر",
    "title_en": "SAJER",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "n3lXdUIKY9Y=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "DARMAA - ضرماء",
    "title_ar": "ضرماء",
    "title_en": "DARMAA",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "ivC0LCf36mk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-ARTAWYAH - الأرطاوية",
    "title_ar": "الأرطاوية",
    "title_en": "AL-ARTAWYAH",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "ZAESJ/5hrXk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "MRAT - مرات",
    "title_ar": "مرات",
    "title_en": "MRAT",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "o/oQEOl+jhg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "HALBAN - حلبان",
    "title_ar": "حلبان",
    "title_en": "HALBAN",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "e65LZndl5pg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الحريق",
    "title_ar": "الحريق",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "XnP6GcAPQTg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الرين",
    "title_ar": "الرين",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "4Qe+dtqn5zg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "طحي",
    "title_ar": "طحي",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "cnnkFXturKk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الحوميات",
    "title_ar": "الحوميات",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "VsyK4ePnIYg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "نفي",
    "title_ar": "نفي",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "v7/Y1uKZNXI=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "مشاش عوض",
    "title_ar": "مشاش عوض",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "4NpFUZYBJg4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "القاعية",
    "title_ar": "القاعية",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "Ysxx8E/JR2A=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الحصاة",
    "title_ar": "الحصاة",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "NjYwXy6JJ+k=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "حفر العتش",
    "title_ar": "حفر العتش",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "nJsCj4L3efA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الحيانية",
    "title_ar": "الحيانية",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "X0jBC0DIMT8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "البجادية",
    "title_ar": "البجادية",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "MWg9CG16zI0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "عنان",
    "title_ar": "عنان",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "vhBVjrMEc8o=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "جو",
    "title_ar": "جو",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "Ji3qqEQjiog=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الجلة وتبراك",
    "title_ar": "الجلة وتبراك",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "DlQYndrYliA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "عروى",
    "title_ar": "عروى",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "Q1buMkhJvj0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "صبحاء",
    "title_ar": "صبحاء",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "jqoOxa/B9oo=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "لبخه",
    "title_ar": "لبخه",
    "title_en": "",
    "citc_region_id": "NV25GlPuOnQ=",
    "name_region": "منطقة الرياض",
    "citc_citie_id": "U4Wq3lqZ8zk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "JEDDAH - جده",
    "title_ar": "جده",
    "title_en": "JEDDAH",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "Nap4gA1tyeY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "MAKKAH - مكه المكرمه",
    "title_ar": "مكه المكرمه",
    "title_en": "MAKKAH",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "oIcaYzeDfQQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "TAIF - الطائف",
    "title_ar": "الطائف",
    "title_en": "TAIF",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "w+mTCW1569Y=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "RABEGH - رابغ",
    "title_ar": "رابغ",
    "title_en": "RABEGH",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "OMkgyM2P/AU=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALLAITH - الليث",
    "title_ar": "الليث",
    "title_en": "ALLAITH",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "1MPKPj3KJ6A=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-KONFOTHA - القنفذه",
    "title_ar": "القنفذه",
    "title_en": "AL-KONFOTHA",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "yhS5iovJB+w=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALKHARMA - الخرمه",
    "title_ar": "الخرمه",
    "title_en": "ALKHARMA",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "GCi3TnKNylY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "RANYAH - رنية",
    "title_ar": "رنية",
    "title_en": "RANYAH",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "fvN+Ngjsbes=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "TRBAH - تربة",
    "title_ar": "تربة",
    "title_en": "TRBAH",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "n1u6+qdUX2A=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "DHAHBAN - ذهبان",
    "title_ar": "ذهبان",
    "title_en": "DHAHBAN",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "pa+mnqUp4N0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALUMAIH - المويه",
    "title_ar": "المويه",
    "title_en": "ALUMAIH",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "ZlWMVk05o8I=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-GMOUM - الجموم",
    "title_ar": "الجموم",
    "title_en": "AL-GMOUM",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "zTKHZmpWqtk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BHRAH - بحرة",
    "title_ar": "بحرة",
    "title_en": "BHRAH",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "N0fij760d7s=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-SHEEBAH - الشعيبة",
    "title_ar": "الشعيبة",
    "title_en": "AL-SHEEBAH",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "vkFudy05dus=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-SHEMESY - الشميسي",
    "title_ar": "الشميسي",
    "title_en": "AL-SHEMESY",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "lOavFuLNWlg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-ARDYAH AL-JANOUBYAH - العرضيةالجنوبية",
    "title_ar": "العرضيةالجنوبية",
    "title_en": "AL-ARDYAH AL-JANOUBYAH",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "/ODDRJPQp9M=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "THOUL - ثول",
    "title_ar": "ثول",
    "title_en": "THOUL",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "TlzCIdWmufE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ظلم",
    "title_ar": "ظلم",
    "title_en": "",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "owly184Xo2A=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الزيمة",
    "title_ar": "الزيمة",
    "title_en": "",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "5Csb8lOktuM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "بقياء",
    "title_ar": "بقياء",
    "title_en": "",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "3xvRxSSdvL4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الكامل",
    "title_ar": "الكامل",
    "title_en": "",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "QrfUxJepoKQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "السر",
    "title_ar": "السر",
    "title_en": "",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "hI7eAEmC1S0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "عشيرة",
    "title_ar": "عشيرة",
    "title_en": "",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "RpkeqaIiXwc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ASFAN - عسفان",
    "title_ar": "عسفان",
    "title_en": "ASFAN",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "B9QdszPcrpQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "MADRAKAH - مدركة",
    "title_ar": "مدركة",
    "title_en": "MADRAKAH",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "XoWiTZQ/Mw4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "خليص",
    "title_ar": "خليص",
    "title_en": "",
    "citc_region_id": "Nap4gA1tyeY=",
    "name_region": "منطقة مكة المكرمة",
    "citc_citie_id": "+utlQP02Umk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "MADINAH - المدينه المنوره",
    "title_ar": "المدينه المنوره",
    "title_en": "MADINAH",
    "citc_region_id": "oIcaYzeDfQQ=",
    "name_region": "منطقة المدينة المنورة",
    "citc_citie_id": "rAy9UhMUw6Y=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "YANBU - ينبع",
    "title_ar": "ينبع",
    "title_en": "YANBU",
    "citc_region_id": "oIcaYzeDfQQ=",
    "name_region": "منطقة المدينة المنورة",
    "citc_citie_id": "okz89EMf3XQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-MAHD - المهد",
    "title_ar": "المهد",
    "title_en": "AL-MAHD",
    "citc_region_id": "oIcaYzeDfQQ=",
    "name_region": "منطقة المدينة المنورة",
    "citc_citie_id": "hp7dmWs+8YY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-OLA - العلا",
    "title_ar": "العلا",
    "title_en": "AL-OLA",
    "citc_region_id": "oIcaYzeDfQQ=",
    "name_region": "منطقة المدينة المنورة",
    "citc_citie_id": "8Bb8tk/IDxA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "KHAYBAR - خيبر",
    "title_ar": "خيبر",
    "title_en": "KHAYBAR",
    "citc_region_id": "oIcaYzeDfQQ=",
    "name_region": "منطقة المدينة المنورة",
    "citc_citie_id": "sbBoFGUGeuI=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-HNAKYAH - الحناكية",
    "title_ar": "الحناكية",
    "title_en": "AL-HNAKYAH",
    "citc_region_id": "oIcaYzeDfQQ=",
    "name_region": "منطقة المدينة المنورة",
    "citc_citie_id": "i2We4j5DRek=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BADER - بدر",
    "title_ar": "بدر",
    "title_en": "BADER",
    "citc_region_id": "oIcaYzeDfQQ=",
    "name_region": "منطقة المدينة المنورة",
    "citc_citie_id": "SQIlmec45sI=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALSOWAIDRAH - الصويدرة",
    "title_ar": "الصويدرة",
    "title_en": "ALSOWAIDRAH",
    "citc_region_id": "oIcaYzeDfQQ=",
    "name_region": "منطقة المدينة المنورة",
    "citc_citie_id": "nITbO+Wqal8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الرايس",
    "title_ar": "الرايس",
    "title_en": "",
    "citc_region_id": "oIcaYzeDfQQ=",
    "name_region": "منطقة المدينة المنورة",
    "citc_citie_id": "2x9Rxk57QXE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "وادي الفرع",
    "title_ar": "وادي الفرع",
    "title_en": "",
    "citc_region_id": "oIcaYzeDfQQ=",
    "name_region": "منطقة المدينة المنورة",
    "citc_citie_id": "Ra6BhUkhWmY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BURAYDAH - بريده",
    "title_ar": "بريده",
    "title_en": "BURAYDAH",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "K752JTDp22o=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ENEZAH - عنيزة",
    "title_ar": "عنيزة",
    "title_en": "ENEZAH",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "ev0RIw5VH1U=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALRAS - الرس",
    "title_ar": "الرس",
    "title_en": "ALRAS",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "CFuRK8sbOJE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-BKERYA - البكيريه",
    "title_ar": "البكيريه",
    "title_en": "AL-BKERYA",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "aMes1QUMOJo=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-MZNB - المذنب",
    "title_ar": "المذنب",
    "title_en": "AL-MZNB",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "AJEP+ilT6EM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-BADAEE - البدائع",
    "title_ar": "البدائع",
    "title_en": "AL-BADAEE",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "Pl5+WxPD/8Y=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AKLAT AL-SKOUR - عقلة الصقور",
    "title_ar": "عقلة الصقور",
    "title_en": "AKLAT AL-SKOUR",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "ULILdfrI1as=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-ASYAH - الاسياح",
    "title_ar": "الاسياح",
    "title_en": "AL-ASYAH",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "EpE6jkbSfD8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "RIYADH ALKHABRA - رياض الخبرا",
    "title_ar": "رياض الخبرا",
    "title_en": "RIYADH ALKHABRA",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "eiAcQxWG6oc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AOWYOON ALJIWA - عيون الجواء",
    "title_ar": "عيون الجواء",
    "title_en": "AOWYOON ALJIWA",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "jriu3Gybp+Y=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "DHERIAH - ضرية",
    "title_ar": "ضرية",
    "title_en": "DHERIAH",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "O/k2F+PbJ0c=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-KOSYBAA - القصيباء",
    "title_ar": "القصيباء",
    "title_en": "AL-KOSYBAA",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "P7YOEbaNfhA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-SHANANA - الشنانة",
    "title_ar": "الشنانة",
    "title_en": "AL-SHANANA",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "qTdsSBUdOHs=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-BATRAA - البتراء",
    "title_ar": "البتراء",
    "title_en": "AL-BATRAA",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "aXQP65zctP8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-SHMASYAH - الشماسية",
    "title_ar": "الشماسية",
    "title_en": "AL-SHMASYAH",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "fG8bbUH50F4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "KBAH - قبة",
    "title_ar": "قبة",
    "title_en": "KBAH",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "IAsWgrw1g1U=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "النبهانية",
    "title_ar": "النبهانية",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "SO2MMH5/yqs=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الشبيكية",
    "title_ar": "الشبيكية",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "ZkHeu+joBL4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الملقاء",
    "title_ar": "الملقاء",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "//gUklR6zTo=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "دخنه",
    "title_ar": "دخنه",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "/s13zVc2pA0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "عطاء",
    "title_ar": "عطاء",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "bcZq9fjPbgE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ابانات",
    "title_ar": "ابانات",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "IRGRvycfFcA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "القواره",
    "title_ar": "القواره",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "HW+8y2sbB/o=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ابا الورود",
    "title_ar": "ابا الورود",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "qMqaA15oLrU=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الظاهرية",
    "title_ar": "الظاهرية",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "F2KHzxwj6gI=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الدليمية",
    "title_ar": "الدليمية",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "5DHxZ0ePiLs=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الصمعورية",
    "title_ar": "الصمعورية",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "DycWfBI0/Hk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "العمار",
    "title_ar": "العمار",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "WtPQalJqhWM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "البطين",
    "title_ar": "البطين",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "ludy1q6g1BQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "شري",
    "title_ar": "شري",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "MHL19FH03JI=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "مدرج",
    "title_ar": "مدرج",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "OI1gZtDBGTA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الذيبية",
    "title_ar": "الذيبية",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "ViZmI4NNZF4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "القرين",
    "title_ar": "القرين",
    "title_en": "",
    "citc_region_id": "w+mTCW1569Y=",
    "name_region": "منطقة القصيم",
    "citc_citie_id": "M/abw/BvAZA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "DAMMAM - الدمام",
    "title_ar": "الدمام",
    "title_en": "DAMMAM",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "vXChcFPkxcI=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-KHUBAR - الخبر",
    "title_ar": "الخبر",
    "title_en": "AL-KHUBAR",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "7kRgMtOkdQE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALHAFOUF - الهفوف",
    "title_ar": "الهفوف",
    "title_en": "ALHAFOUF",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "cABXRPle08s=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-KATEEF - القطيف",
    "title_ar": "القطيف",
    "title_en": "AL-KATEEF",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "i07AZC3Axw4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-JUBAIL - الجبيل",
    "title_ar": "الجبيل",
    "title_en": "AL-JUBAIL",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "rHYWCxiMFVY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "KARYA - قريه",
    "title_ar": "قريه",
    "title_en": "KARYA",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "ovCU0jF3K78=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "HAFR ALBATIN - حفر الباطن",
    "title_ar": "حفر الباطن",
    "title_en": "HAFR ALBATIN",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "3E29T521tWk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALKHAFJI - الخفجي",
    "title_ar": "الخفجي",
    "title_en": "ALKHAFJI",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "y5zgJK9KaT0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-NAERYAH - النعيرية",
    "title_ar": "النعيرية",
    "title_en": "AL-NAERYAH",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "uUS+BzFxoC4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "RAAS TANOURAH - رأس تنورة",
    "title_ar": "رأس تنورة",
    "title_en": "RAAS TANOURAH",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "ZA3W9AKCPSk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BAKEEK - بقيق",
    "title_ar": "بقيق",
    "title_en": "BAKEEK",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "kr7gPRhygSI=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-ZAHRAN - الظهران",
    "title_ar": "الظهران",
    "title_en": "AL-ZAHRAN",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "DkWZ7cZi+yc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-RAKEE - منفذ الرقعي",
    "title_ar": "منفذ الرقعي",
    "title_en": "AL-RAKEE",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "LTsD0V8q980=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "KING FAHAD CAUSEWAY - جسر الملك فهد",
    "title_ar": "جسر الملك فهد",
    "title_en": "KING FAHAD CAUSEWAY",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "yuZANuOO7l4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SALWA - سلوى",
    "title_ar": "سلوى",
    "title_en": "SALWA",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "mlOYxJuUua8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALADEED - العديد",
    "title_ar": "العديد",
    "title_en": "ALADEED",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "+l2R99BiTXY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BATHA - بطحاء",
    "title_ar": "بطحاء",
    "title_en": "BATHA",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "XnEfmRzm+EY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SAFWA - صفوى",
    "title_ar": "صفوى",
    "title_en": "SAFWA",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "FrYsF5UGGN4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SEEHAT - سيهات",
    "title_ar": "سيهات",
    "title_en": "SEEHAT",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "w1V6rte0qXA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "TAROUT - تاروت",
    "title_ar": "تاروت",
    "title_en": "TAROUT",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "M3T52TB6kFM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "السعيرة",
    "title_ar": "السعيرة",
    "title_en": "",
    "citc_region_id": "rAy9UhMUw6Y=",
    "name_region": "المنطقة الشرقية",
    "citc_citie_id": "cixVoDzk+uY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ABHA - ابها",
    "title_ar": "ابها",
    "title_en": "ABHA",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "xn0UMTPfYuc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALBRK - البرك",
    "title_ar": "البرك",
    "title_en": "ALBRK",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "nhzYnXxZcpw=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "KHAMEES MSHEET - خميس مشيط",
    "title_ar": "خميس مشيط",
    "title_en": "KHAMEES MSHEET",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "W41vEgPgp5E=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ZAHRAN AL-JANOUB - ظهران الجنوب",
    "title_ar": "ظهران الجنوب",
    "title_en": "ZAHRAN AL-JANOUB",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "qC28Vf3bm/4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-NMAS - النماص",
    "title_ar": "النماص",
    "title_en": "AL-NMAS",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "BIP9W1+l9v0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "REJAL ALMAA - رجال ألمع",
    "title_ar": "رجال ألمع",
    "title_en": "REJAL ALMAA",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "KJsripOFtkA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BESHAH - بيشه",
    "title_ar": "بيشه",
    "title_en": "BESHAH",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "tLWTlL35LLc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "MAHAEL ASEER - محائل عسير",
    "title_ar": "محائل عسير",
    "title_en": "MAHAEL ASEER",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "ZP0f5SdZ2ZE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BLKARN - بلقرن",
    "title_ar": "بلقرن",
    "title_en": "BLKARN",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "gSTV+jSYKBs=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SABT AL-ALAYAH - سبت العلايه",
    "title_ar": "سبت العلايه",
    "title_en": "SABT AL-ALAYAH",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "Hp63dnraRew=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "TATHLEETH - تثليث",
    "title_ar": "تثليث",
    "title_en": "TATHLEETH",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "tJkF8gq8GSM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SRAT EBEIDAH - سراة عبيدة",
    "title_ar": "سراة عبيدة",
    "title_en": "SRAT EBEIDAH",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "zkL8HH0A+/4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALB - علب",
    "title_ar": "علب",
    "title_en": "ALB",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "mhSLFnUE6Kc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "OHOD RFEDAH - أحدرفيدة",
    "title_ar": "أحدرفيدة",
    "title_en": "OHOD RFEDAH",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "HVAGmlxWJkk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-HREDAH - الحريضة",
    "title_ar": "الحريضة",
    "title_en": "AL-HREDAH",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "c+EZiuy3yiY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BLSAMAR - باللسمر",
    "title_ar": "باللسمر",
    "title_en": "BLSAMAR",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "Mw/ufMI3Yaw=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-MJARDAH - المجاردة",
    "title_ar": "المجاردة",
    "title_en": "AL-MJARDAH",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "FSivbDL0oVE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BLHAMR - باللحمر",
    "title_ar": "باللحمر",
    "title_en": "BLHAMR",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "2Has9DG7PG0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALJWA - الجوة",
    "title_ar": "الجوة",
    "title_en": "ALJWA",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "NYpx/py9Ics=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-MASKA - المسقي",
    "title_ar": "المسقي",
    "title_en": "AL-MASKA",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "C69hLKsrAXs=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "KNAA WLBAHR - قناءوالبحر",
    "title_ar": "قناءوالبحر",
    "title_en": "KNAA WLBAHR",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "Kkph49A7PSk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "WADY HSHBL - وادي هشبل",
    "title_ar": "وادي هشبل",
    "title_en": "WADY HSHBL",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "Lxwd4uRdEe4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BANY AMR - بني عمرو",
    "title_ar": "بني عمرو",
    "title_en": "BANY AMR",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "wsWx8yIz/9Q=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-BASHAYER - البشاير",
    "title_ar": "البشاير",
    "title_en": "AL-BASHAYER",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "pzak/O+t5G8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "TNOMAH - تنومة",
    "title_ar": "تنومة",
    "title_en": "TNOMAH",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "bLeYrl+WPFA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BAREK - بارق",
    "title_ar": "بارق",
    "title_en": "BAREK",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "CljzZXtNkhk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-FTEHAH - الفطيحة",
    "title_ar": "الفطيحة",
    "title_en": "AL-FTEHAH",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "QwYpGYfxBb0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الشعف",
    "title_ar": "الشعف",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "ZRBYmxDc7eM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "طريب",
    "title_ar": "طريب",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "1Hqm5XfeBio=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الخنقة",
    "title_ar": "الخنقة",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "RmaYiONCMBo=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الخثعم",
    "title_ar": "الخثعم",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "JPBHXMwIcCk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "السرح",
    "title_ar": "السرح",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "CqVqHCrHfU0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الحرجة",
    "title_ar": "الحرجة",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "rdstdtQBbGM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "مرية",
    "title_ar": "مرية",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "AhIFNn0tJ9M=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "باشوت",
    "title_ar": "باشوت",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "aQaS846ippo=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "بحر ابو سكينه",
    "title_ar": "بحر ابو سكينه",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "me/DEchzveo=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "عفراء",
    "title_ar": "عفراء",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "upf7ti9I1NA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "تهامة باللحمر وباللسمر",
    "title_ar": "تهامة باللحمر وباللسمر",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "a3Lhs/xNn4E=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "العرين",
    "title_ar": "العرين",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "RqzmBbfdYAw=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "المضه",
    "title_ar": "المضه",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "LsuH3/ACc4M=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "القحمة",
    "title_ar": "القحمة",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "lPCDNjMczzQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "مدينة سلطان",
    "title_ar": "مدينة سلطان",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "jL8nG5obwJk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "رغوه",
    "title_ar": "رغوه",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "Ok0MXXpyXsM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الأمواه",
    "title_ar": "الأمواه",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "6/X4fCk7uXk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "سعيدة الصوالحه",
    "title_ar": "سعيدة الصوالحه",
    "title_en": "",
    "citc_region_id": "A/VaSUhyG28=",
    "name_region": "منطقة عسير",
    "citc_citie_id": "N4YhteyvlyY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "HAIL - حائل",
    "title_ar": "حائل",
    "title_en": "HAIL",
    "citc_region_id": "vXChcFPkxcI=",
    "name_region": "منطقة حائل",
    "citc_citie_id": "J4DRtp+fYEM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BAKAA - بقعاء",
    "title_ar": "بقعاء",
    "title_en": "BAKAA",
    "citc_region_id": "vXChcFPkxcI=",
    "name_region": "منطقة حائل",
    "citc_citie_id": "QL+gWf62PKE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "JUBAH - جبه",
    "title_ar": "جبه",
    "title_en": "JUBAH",
    "citc_region_id": "vXChcFPkxcI=",
    "name_region": "منطقة حائل",
    "citc_citie_id": "463Y+Lm0TfA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-GHAZALAH - الغزالة",
    "title_ar": "الغزالة",
    "title_en": "AL-GHAZALAH",
    "citc_region_id": "vXChcFPkxcI=",
    "name_region": "منطقة حائل",
    "citc_citie_id": "Le+EdLetmQg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALKHTAH - الخطة",
    "title_ar": "الخطة",
    "title_en": "ALKHTAH",
    "citc_region_id": "vXChcFPkxcI=",
    "name_region": "منطقة حائل",
    "citc_citie_id": "unnsOHfahIU=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-SHMLY - الشملي",
    "title_ar": "الشملي",
    "title_en": "AL-SHMLY",
    "citc_region_id": "vXChcFPkxcI=",
    "name_region": "منطقة حائل",
    "citc_citie_id": "6d5WZ38NNzQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-SHNAN - الشنان",
    "title_ar": "الشنان",
    "title_en": "AL-SHNAN",
    "citc_region_id": "vXChcFPkxcI=",
    "name_region": "منطقة حائل",
    "citc_citie_id": "n67ydMmfMps=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الحليفة",
    "title_ar": "الحليفة",
    "title_en": "",
    "citc_region_id": "vXChcFPkxcI=",
    "name_region": "منطقة حائل",
    "citc_citie_id": "+nvazNaLpSc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "موقق",
    "title_ar": "موقق",
    "title_en": "",
    "citc_region_id": "vXChcFPkxcI=",
    "name_region": "منطقة حائل",
    "citc_citie_id": "Rg2CyA/GAvA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الغزالة",
    "title_ar": "الغزالة",
    "title_en": "",
    "citc_region_id": "vXChcFPkxcI=",
    "name_region": "منطقة حائل",
    "citc_citie_id": "PRnJ6GHes6U=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "TABOUK - تبوك",
    "title_ar": "تبوك",
    "title_en": "TABOUK",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "A/VaSUhyG28=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "TAIMAA - تيماء",
    "title_ar": "تيماء",
    "title_en": "TAIMAA",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "URu+15ccXlY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "DEBAA - ضباء",
    "title_ar": "ضباء",
    "title_en": "DEBAA",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "F4R9fYSZjQ8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALWJH - الوجه",
    "title_ar": "الوجه",
    "title_en": "ALWJH",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "yJ/zQir/+hs=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AMLJ - أملج",
    "title_ar": "أملج",
    "title_en": "AMLJ",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "47cSMYC2mpg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "HAKL - حقل",
    "title_ar": "حقل",
    "title_en": "HAKL",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "6yiJsZbDlhI=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALDORRA - الدره",
    "title_ar": "الدره",
    "title_en": "ALDORRA",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "0LRGsy/SjxM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "HALUT AMMAR - حالة عمار",
    "title_ar": "حالة عمار",
    "title_en": "HALUT AMMAR",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "E1zKGY87xkI=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-BEDE - البدع",
    "title_ar": "البدع",
    "title_en": "AL-BEDE",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "p7fNvgUGzxg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BEER BN HRMAS - بئربن هرماس",
    "title_ar": "بئربن هرماس",
    "title_en": "BEER BN HRMAS",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "Z/B9eO6DiPQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "الجهراء",
    "title_ar": "الجهراء",
    "title_en": "",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "xecokLZmkyM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "شرمأ",
    "title_ar": "شرمأ",
    "title_en": "",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "cSdlB1xvgw0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "شقري",
    "title_ar": "شقري",
    "title_en": "",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "5/VDmeydy2w=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALSHABHA - الشبحة",
    "title_ar": "الشبحة",
    "title_en": "ALSHABHA",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "0GsQWu1j0F0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BEDA - بدا",
    "title_ar": "بدا",
    "title_en": "BEDA",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "tR+lbBvDhwA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALMANJOR - المنجور",
    "title_ar": "المنجور",
    "title_en": "ALMANJOR",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "/6kLct/GwNA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ASHWAQ - أشواق",
    "title_ar": "أشواق",
    "title_en": "ASHWAQ",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "nX0KczcFg94=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ABO RAKAH - أبو راكة",
    "title_ar": "أبو راكة",
    "title_en": "ABO RAKAH",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "TY1Kaabg0Hc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "QLIBAH - القليبة",
    "title_ar": "القليبة",
    "title_en": "QLIBAH",
    "citc_region_id": "7kRgMtOkdQE=",
    "name_region": "منطقة تبوك",
    "citc_citie_id": "fnMTVg6d2u4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BAHA - الباحه",
    "title_ar": "الباحه",
    "title_en": "BAHA",
    "citc_region_id": "cABXRPle08s=",
    "name_region": "منطقة الباحة",
    "citc_citie_id": "M5ltI0k+yXg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "KALWAH - قلوه",
    "title_ar": "قلوه",
    "title_en": "KALWAH",
    "citc_region_id": "cABXRPle08s=",
    "name_region": "منطقة الباحة",
    "citc_citie_id": "C/T445xdx5c=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-MANDAK - المندق",
    "title_ar": "المندق",
    "title_en": "AL-MANDAK",
    "citc_region_id": "cABXRPle08s=",
    "name_region": "منطقة الباحة",
    "citc_citie_id": "3wp1k8Avk2M=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BLGRSHY - بلجرشي",
    "title_ar": "بلجرشي",
    "title_en": "BLGRSHY",
    "citc_region_id": "cABXRPle08s=",
    "name_region": "منطقة الباحة",
    "citc_citie_id": "4uwWDVw0yRE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-MKHWAH - المخواة",
    "title_ar": "المخواة",
    "title_en": "AL-MKHWAH",
    "citc_region_id": "cABXRPle08s=",
    "name_region": "منطقة الباحة",
    "citc_citie_id": "RzC4TIyAr8Q=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALQORA - القرى",
    "title_ar": "القرى",
    "title_en": "ALQORA",
    "citc_region_id": "cABXRPle08s=",
    "name_region": "منطقة الباحة",
    "citc_citie_id": "fBAWvSuAFUA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-AKEEK - العقيق",
    "title_ar": "العقيق",
    "title_en": "AL-AKEEK",
    "citc_region_id": "cABXRPle08s=",
    "name_region": "منطقة الباحة",
    "citc_citie_id": "7N8CxGJucAM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "HAJRAH - الحجرة",
    "title_ar": "الحجرة",
    "title_en": "HAJRAH",
    "citc_region_id": "cABXRPle08s=",
    "name_region": "منطقة الباحة",
    "citc_citie_id": "hvGpRArIGNw=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BNI HASAN - بني حسن",
    "title_ar": "بني حسن",
    "title_en": "BNI HASAN",
    "citc_region_id": "cABXRPle08s=",
    "name_region": "منطقة الباحة",
    "citc_citie_id": "VUzR4eMUCSI=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BNI KABEER - بني كبير",
    "title_ar": "بني كبير",
    "title_en": "BNI KABEER",
    "citc_region_id": "cABXRPle08s=",
    "name_region": "منطقة الباحة",
    "citc_citie_id": "c4YY9zxujUc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "KAMED ALZNAD - غامد الزناد",
    "title_ar": "غامد الزناد",
    "title_en": "KAMED ALZNAD",
    "citc_region_id": "cABXRPle08s=",
    "name_region": "منطقة الباحة",
    "citc_citie_id": "S+YXk2XcLxQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "MASHOKAH - معشوقة",
    "title_ar": "معشوقة",
    "title_en": "MASHOKAH",
    "citc_region_id": "cABXRPle08s=",
    "name_region": "منطقة الباحة",
    "citc_citie_id": "uvHZlfI8HBU=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BAHA - الباحه",
    "title_ar": "الباحه",
    "title_en": "BAHA",
    "citc_region_id": "K752JTDp22o=",
    "name_region": "منطقة الحدود الشمالية",
    "citc_citie_id": "M5ltI0k+yXg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "KALWAH - قلوه",
    "title_ar": "قلوه",
    "title_en": "KALWAH",
    "citc_region_id": "K752JTDp22o=",
    "name_region": "منطقة الحدود الشمالية",
    "citc_citie_id": "C/T445xdx5c=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-MANDAK - المندق",
    "title_ar": "المندق",
    "title_en": "AL-MANDAK",
    "citc_region_id": "K752JTDp22o=",
    "name_region": "منطقة الحدود الشمالية",
    "citc_citie_id": "3wp1k8Avk2M=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BLGRSHY - بلجرشي",
    "title_ar": "بلجرشي",
    "title_en": "BLGRSHY",
    "citc_region_id": "K752JTDp22o=",
    "name_region": "منطقة الحدود الشمالية",
    "citc_citie_id": "4uwWDVw0yRE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-MKHWAH - المخواة",
    "title_ar": "المخواة",
    "title_en": "AL-MKHWAH",
    "citc_region_id": "K752JTDp22o=",
    "name_region": "منطقة الحدود الشمالية",
    "citc_citie_id": "RzC4TIyAr8Q=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALQORA - القرى",
    "title_ar": "القرى",
    "title_en": "ALQORA",
    "citc_region_id": "K752JTDp22o=",
    "name_region": "منطقة الحدود الشمالية",
    "citc_citie_id": "fBAWvSuAFUA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-AKEEK - العقيق",
    "title_ar": "العقيق",
    "title_en": "AL-AKEEK",
    "citc_region_id": "K752JTDp22o=",
    "name_region": "منطقة الحدود الشمالية",
    "citc_citie_id": "7N8CxGJucAM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "HAJRAH - الحجرة",
    "title_ar": "الحجرة",
    "title_en": "HAJRAH",
    "citc_region_id": "K752JTDp22o=",
    "name_region": "منطقة الحدود الشمالية",
    "citc_citie_id": "hvGpRArIGNw=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BNI HASAN - بني حسن",
    "title_ar": "بني حسن",
    "title_en": "BNI HASAN",
    "citc_region_id": "K752JTDp22o=",
    "name_region": "منطقة الحدود الشمالية",
    "citc_citie_id": "VUzR4eMUCSI=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BNI KABEER - بني كبير",
    "title_ar": "بني كبير",
    "title_en": "BNI KABEER",
    "citc_region_id": "K752JTDp22o=",
    "name_region": "منطقة الحدود الشمالية",
    "citc_citie_id": "c4YY9zxujUc=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "KAMED ALZNAD - غامد الزناد",
    "title_ar": "غامد الزناد",
    "title_en": "KAMED ALZNAD",
    "citc_region_id": "K752JTDp22o=",
    "name_region": "منطقة الحدود الشمالية",
    "citc_citie_id": "S+YXk2XcLxQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "MASHOKAH - معشوقة",
    "title_ar": "معشوقة",
    "title_en": "MASHOKAH",
    "citc_region_id": "K752JTDp22o=",
    "name_region": "منطقة الحدود الشمالية",
    "citc_citie_id": "uvHZlfI8HBU=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALJOWF - سكاكا",
    "title_ar": "سكاكا",
    "title_en": "ALJOWF",
    "citc_region_id": "J4DRtp+fYEM=",
    "name_region": "منطقة الجوف",
    "citc_citie_id": "/LqYLqydJPI=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "DAWMAT AL-JANDAL - دومة الجندل",
    "title_ar": "دومة الجندل",
    "title_en": "DAWMAT AL-JANDAL",
    "citc_region_id": "J4DRtp+fYEM=",
    "name_region": "منطقة الجوف",
    "citc_citie_id": "cRTcuQjgkbM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "TABARJAL - طبرجل",
    "title_ar": "طبرجل",
    "title_en": "TABARJAL",
    "citc_region_id": "J4DRtp+fYEM=",
    "name_region": "منطقة الجوف",
    "citc_citie_id": "99P5v0FFAq0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALQURAYAT - القريات",
    "title_ar": "القريات",
    "title_en": "ALQURAYAT",
    "citc_region_id": "J4DRtp+fYEM=",
    "name_region": "منطقة الجوف",
    "citc_citie_id": "TnE6TB2ePys=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALHADEETHA - الحديثه",
    "title_ar": "الحديثه",
    "title_en": "ALHADEETHA",
    "citc_region_id": "J4DRtp+fYEM=",
    "name_region": "منطقة الجوف",
    "citc_citie_id": "7/5cgNIO4qU=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "طلعة عمار",
    "title_ar": "طلعة عمار",
    "title_en": "",
    "citc_region_id": "J4DRtp+fYEM=",
    "name_region": "منطقة الجوف",
    "citc_citie_id": "0oJSKeq/BHE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "JAZAN - جازان",
    "title_ar": "جازان",
    "title_en": "JAZAN",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "QwbfoYc1guQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SAMTAH - صامطه",
    "title_ar": "صامطه",
    "title_en": "SAMTAH",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "vcW8rcGG38w=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SBYAA - صبياء",
    "title_ar": "صبياء",
    "title_en": "SBYAA",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "egwyzIcO9uE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ABY AREESH - أبي عريش",
    "title_ar": "أبي عريش",
    "title_en": "ABY AREESH",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "lr3Dcay4CqQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "FRSAN - فرسان",
    "title_ar": "فرسان",
    "title_en": "FRSAN",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "MiluPe6OXt8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-DARB - الدرب",
    "title_ar": "الدرب",
    "title_en": "AL-DARB",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "kKHn15G1grY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALTWAL - منفذ الطوال",
    "title_ar": "منفذ الطوال",
    "title_en": "ALTWAL",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "3r4daipaWyQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALMOWASSAM - الموسم",
    "title_ar": "الموسم",
    "title_en": "ALMOWASSAM",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "kvd5//gBgo8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-RETH - الريث",
    "title_ar": "الريث",
    "title_en": "AL-RETH",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "XkRkJQqUwHQ=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "OHOD AL-MASARHA - احدالمسارحة",
    "title_ar": "احدالمسارحة",
    "title_en": "OHOD AL-MASARHA",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "L4ePfER4yhA=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALHARTH - الحرث",
    "title_ar": "الحرث",
    "title_en": "ALHARTH",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "MsB7PXiBKJY=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-AARDAH - العارضة",
    "title_ar": "العارضة",
    "title_en": "AL-AARDAH",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "mbKpFe918uo=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "BEESH - بيش",
    "title_ar": "بيش",
    "title_en": "BEESH",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "xNM/BnQzwlo=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "FIFAA - فيفاء",
    "title_ar": "فيفاء",
    "title_en": "FIFAA",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "KuWX8zr3t2s=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-MADAYA - المضايا",
    "title_ar": "المضايا",
    "title_en": "AL-MADAYA",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "k8izRCz1hz0=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "WADI JAZAN - وادي جازان",
    "title_ar": "وادي جازان",
    "title_en": "WADI JAZAN",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "1h0qoR/n62Y=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-DAAER - الدائر",
    "title_ar": "الدائر",
    "title_en": "AL-DAAER",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "sZvYZMGpGqs=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "DMD - ضمد",
    "title_ar": "ضمد",
    "title_en": "DMD",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "crj6KLipvic=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-SHKEK BJEZAN - الشقيق بجازان",
    "title_ar": "الشقيق بجازان",
    "title_en": "AL-SHKEK BJEZAN",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "FX24SgPkSt4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "العيدابي",
    "title_ar": "العيدابي",
    "title_en": "",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "xz2FN75wz/E=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "HROB - هروب",
    "title_ar": "هروب",
    "title_en": "HROB",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "0i+taXPKcGM=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SAHLI - السهي",
    "title_ar": "السهي",
    "title_en": "SAHLI",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "CgDiL9geDjU=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALIAH - العالية",
    "title_ar": "العالية",
    "title_en": "ALIAH",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "/ccW6HRkLW4=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALHAQO - الحقو",
    "title_ar": "الحقو",
    "title_en": "ALHAQO",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "5Qnut27awLg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "GOZ ALJAFRAH - قوز الجعافرة",
    "title_ar": "قوز الجعافرة",
    "title_en": "GOZ ALJAFRAH",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "W+u0VNrBI80=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALQAFL - القفل",
    "title_ar": "القفل",
    "title_en": "ALQAFL",
    "citc_region_id": "lC6Xv4MKJA8=",
    "name_region": "منطقة جازان",
    "citc_citie_id": "ct9P+jesXUg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "NAJRAN - نجران",
    "title_ar": "نجران",
    "title_en": "NAJRAN",
    "citc_region_id": "xn0UMTPfYuc=",
    "name_region": "منطقة نجران",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "SHAROURAH - شرورة",
    "title_ar": "شرورة",
    "title_en": "SHAROURAH",
    "citc_region_id": "xn0UMTPfYuc=",
    "name_region": "منطقة نجران",
    "citc_citie_id": "vPhEuw0fVeU=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ALKHADHRA - منفذ الخضراء",
    "title_ar": "منفذ الخضراء",
    "title_en": "ALKHADHRA",
    "citc_region_id": "xn0UMTPfYuc=",
    "name_region": "منطقة نجران",
    "citc_citie_id": "eOohGPW/gRo=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "HBOUNA - حبونا",
    "title_ar": "حبونا",
    "title_en": "HBOUNA",
    "citc_region_id": "xn0UMTPfYuc=",
    "name_region": "منطقة نجران",
    "citc_citie_id": "UMW5Q8vAawg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-KHARKHER - الخرخير",
    "title_ar": "الخرخير",
    "title_en": "AL-KHARKHER",
    "citc_region_id": "xn0UMTPfYuc=",
    "name_region": "منطقة نجران",
    "citc_citie_id": "PCL0+veeTqs=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-WADEAAH - منفذ الوديعة",
    "title_ar": "منفذ الوديعة",
    "title_en": "AL-WADEAAH",
    "citc_region_id": "xn0UMTPfYuc=",
    "name_region": "منطقة نجران",
    "citc_citie_id": "Y1UppKg7Ynk=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-AREESAH - العريسة",
    "title_ar": "العريسة",
    "title_en": "AL-AREESAH",
    "citc_region_id": "xn0UMTPfYuc=",
    "name_region": "منطقة نجران",
    "citc_citie_id": "JLQChrQhNWg=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "AL-HSENYAH - الحصينية",
    "title_ar": "الحصينية",
    "title_en": "AL-HSENYAH",
    "citc_region_id": "xn0UMTPfYuc=",
    "name_region": "منطقة نجران",
    "citc_citie_id": "5TvNiVuTp9Q=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "يدمه",
    "title_ar": "يدمه",
    "title_en": "",
    "citc_region_id": "xn0UMTPfYuc=",
    "name_region": "منطقة نجران",
    "citc_citie_id": "x1nUrDDdzhE=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "ثار",
    "title_ar": "ثار",
    "title_en": "",
    "citc_region_id": "xn0UMTPfYuc=",
    "name_region": "منطقة نجران",
    "citc_citie_id": "OGQeGEkgPh8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "بدر الجنوب",
    "title_ar": "بدر الجنوب",
    "title_en": "",
    "citc_region_id": "xn0UMTPfYuc=",
    "name_region": "منطقة نجران",
    "citc_citie_id": "fr4LNLkJyk8=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  },
  {
    "name": "خباش",
    "title_ar": "خباش",
    "title_en": "",
    "citc_region_id": "xn0UMTPfYuc=",
    "name_region": "منطقة نجران",
    "citc_citie_id": "W3T8gRx/z7E=",
    "latitude": 0,
    "longitude": 0,
    "country_id": 1,
    "lang_file": "en"
  }
]
